version: 2
jobs:
  build:
    working_directory: /app
    branches:
      only:
        - master

    docker:
      - image: docker:latest

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Build Docker Image
          command: docker build -t ${DOCKER_REPO}/relay:latest .

      - run:
          name: Authenticate With Cloudsmith 
          command: |
              echo ${CLOUDSMITH_API_KEY} | docker login docker.cloudsmith.io -u ${CLOUDSMITH_USER} --password-stdin

      - run:
          name: Push Docker Image
          command: docker push ${DOCKER_REPO}/relay:latest
