version: 2
jobs:
  build:
    working_directory: /app

    docker:
      - image: docker:latest

    steps:
      - checkout

      - setup_remote_docker

      - run:
        name: Build Docker Image
        command: docker build -t ${DOCKER_REPO}/relay:latest .

      - run:
        name: Authenticate With Cloudsmith 
        command: |
            docker login docker.cloudsmith.io -u ${CLOUDSMITH_USER} -p ${CLOUDSMITH_API_KEY}

      - run:
        name: Push Docker Image
        command: docker push ${DOCKER_REPO}/relay:latest .
